# AWS Credentials for Text-to-Speech functionality
# Replace these with your actual AWS credentials if you want to use the voice features
aws_access_key_id = "your aws access key"
aws_secret_access_key = "your aws secret access key"

# OpenAI API Key (required for AI features)
# Replace with your actual OpenAI API key
OPENAI_API_KEY = "openai api key" 
